# for development environment on local PC

cloud:
  aws:
    # AWS common
    region:
      static: ap-northeast-1
      auto: false
    credentials:
      instanceProfile: false
    # DynamoDB
    dynamodb:
      # DynamoDBは同一テーブル名を使用しているため、環境毎にリージョン、もしくはAWSアカウントを切り替える。
      region: ap-northeast-1
    # SQS
    sqs:
      region: ap-northeast-1
    # CloudWatch
    cloudwatch:
      region: ${cloud.aws.region.static}

# RDB(ローカルPC上のPostgreSQLを使用)
database:
  # RDSのリージョン設定
  rdsRegion: ${cloud.aws.region.static}
  common:
    data-source:
      # 各DBの共通設定
      driverClassName: org.postgresql.Driver
      maxActive: 96
      maxIdle: 16
      minIdle: 16
      initialSize: 16
      maxWait: 90000
      password: postgres
      username: postgres
      validationQuery: SELECT 1
      testOnConnect: true
      testWhileIdle: true
      # Amazon failover の最大値
      # 参考 [http://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html]
      timeBetweenEvictionRunsMillis: 120000
      removeAbandoned: true
      removeAbandonedTimeout: 60
  default:
    schema:
      name: default
  data-sources:
    - schema: default
      url: jdbc:postgresql://localhost:5432/atrs?socketTimeout=120&connectTimeout=120
    - schema: atrs1
      url: jdbc:postgresql://localhost:5432/atrs1?socketTimeout=120&connectTimeout=120
    - schema: atrs2
      url: jdbc:postgresql://localhost:5432/atrs2?socketTimeout=120&connectTimeout=120

# upload directories
upload:
  bucketName: atrs.upload.private.dev
  temporaryDirectory: tmp/
  saveDirectory: save/

# SQS queue name
reservation:
  notification:
    # 環境毎にキューを切り替える。
    queue: RESERVATION_NOTICE

# static contents for local(ローカル資材を利用)
content:
  url: /atrs

# Logging
logging:
  path: /var/log/atrslogs
  # Workaround for duplicated log files
  config: classpath:atrs-logback-spring.xml

# RedisMessageListenerContainerのconcurrencyLimit設定
spring:
  redis:
    listener:
      concurrencyLimit: 2

# Redis(Session用/Cache用)
redis:
  session:
    server: 127.0.0.1
    port: 6379
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1
    minIdle: 0
  cache:
    server: 127.0.0.1
    port: 6379
    maxTotal: 8
    maxIdle: 8
    maxWaitMillis: -1
    minIdle: 0