# 環境依存しないフレームワークの設定値

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: atrs
  session:
    store-type: redis

# codelist
cron:
  codelist:
    refreshTime: 0 1 0 * * *

# AWS common
cloud:
  aws:
    credentials:
      accesskey: ${aws.access.key.id}
      secretkey: ${aws.secret.access.key}
    stack:
      auto: false
    # CloudWatch
    cloudwatch:
      namespace: ${spring.profiles.active:local}

# actuator
management:
  endpoints:
    web:
      base-path: /management
    # Set all actuator endpoints disabled by default
    enabled-by-default: false
  endpoint:
    health:
      # Disable sensitive filter for the health endpoint
      show-details: ALWAYS
      # Enable only health endpoint
      enabled: true
  health:
    dynamodb:
      enabled: true
