BEGIN;


CREATE TABLE RESERVE_FLIGHT (
  RESERVE_FLIGHT_NO INT NOT NULL,
  RESERVE_NO VARCHAR(10) NOT NULL,
  DEPARTURE_DATE DATE NOT NULL,
  FLIGHT_NAME VARCHAR(6) NOT NULL,
  BOARDING_CLASS_CD VARCHAR(1) NOT NULL,
  FARE_TYPE_CD VARCHAR(4) NOT NULL
);

ALTER TABLE RESERVE_FLIGHT ADD CONSTRAINT PK_RESERVE_FLIGHT PRIMARY KEY (RESERVE_FLIGHT_NO);



CREATE TABLE RESERVATION (
  RESERVE_NO VARCHAR(10) NOT NULL,
  RESERVE_DATE DATE NOT NULL,
  TOTAL_FARE INT NOT NULL,
  REP_FAMILY_NAME VARCHAR(10) NOT NULL,
  REP_GIVEN_NAME VARCHAR(10) NOT NULL,
  REP_AGE INT NOT NULL,
  REP_GENDER VARCHAR(1) NOT NULL,
  REP_TEL VARCHAR(13) NOT NULL,
  REP_MAIL VARCHAR(256) NOT NULL,
  REP_CUSTOMER_NO VARCHAR(10)
);

ALTER TABLE RESERVATION ADD CONSTRAINT PK_RESERVATION PRIMARY KEY (RESERVE_NO);

CREATE TABLE PASSENGER (
  PASSENGER_NO INT NOT NULL,
  RESERVE_FLIGHT_NO INT NOT NULL,
  FAMILY_NAME VARCHAR(10) NOT NULL,
  GIVEN_NAME VARCHAR(10) NOT NULL,
  AGE INT NOT NULL,
  GENDER VARCHAR(1) NOT NULL,
  CUSTOMER_NO VARCHAR(10)
);

ALTER TABLE PASSENGER ADD CONSTRAINT PK_PASSENGER PRIMARY KEY (PASSENGER_NO);




ALTER TABLE RESERVE_FLIGHT ADD CONSTRAINT FK_RESERVE_FLIGHT_1 FOREIGN KEY (RESERVE_NO) REFERENCES RESERVATION (RESERVE_NO);




ALTER TABLE PASSENGER ADD CONSTRAINT FK_PASSENGER_1 FOREIGN KEY (RESERVE_FLIGHT_NO) REFERENCES RESERVE_FLIGHT (RESERVE_FLIGHT_NO);



CREATE SEQUENCE SQ_RESERVATION_1 MINVALUE 1 MAXVALUE 9999999999 CYCLE;
CREATE SEQUENCE SQ_RESERVE_FLIGHT_1 MINVALUE 1 MAXVALUE 999999999999 CYCLE;
CREATE SEQUENCE SQ_PASSENGER_1 MINVALUE 1 MAXVALUE 9999999999999 CYCLE;

COMMIT;